spring.application.name=virtual-thread-demo

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/virtual_thread_demo
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=20

spring.threads.virtual.enabled=true